definitions:
  handlers.EchoRequest:
    properties:
      message:
        example: Hello!
        type: string
    type: object
  handlers.EchoResponse:
    properties:
      echo:
        type: string
    type: object
info:
  contact: {}
  title: Gin Swagger Example
paths:
  /:
    get:
      description: Проверка работы сервера
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Root endpoint
      tags:
      - system
  /echo:
    post:
      consumes:
      - application/json
      description: Повторяет сообщение из тела запроса
      parameters:
      - description: Message payload
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handlers.EchoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.EchoResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Echo message
      tags:
      - demo
  /health:
    get:
      description: Проверка состояния сервера
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
      - system
  /hello/{name}:
    get:
      description: Приветствие пользователя по имени
      parameters:
      - description: Имя пользователя
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Hello by name
      tags:
      - demo
swagger: "2.0"
